name: Web UI Test Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  run-web-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Grant permission to execute Gradle
        run: chmod +x ./gradlew

      - name: Run UI Tests
        run: ./gradlew test

      - name: List Report Files (Debug)
        run: ls -R target/web || echo "No report files found"

      - name: Upload Cucumber Reports (HTML + JSON)
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cucumber-reports
          path: |
            target/web/cucumber-html-report.html
            target/web/cucumber-report.json